version: '3'
services:
  nginx:
    image: nginx:alpine
    command: >
      /bin/sh -c
        "envsubst ' \
        ' < /etc/nginx/server.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    working_dir: /var/www/html
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/server.conf.template:/etc/nginx/server.conf.template
      - ./src/project:/var/www/html
    #restart: always
    depends_on:
      - php-fpm
    environment:
      - VIRTUAL_HOST=hogehoge.localnet
    env_file:
      - ./nginx/conf/env
  php-fpm:
    build:
      dockerfile: Dockerfile
      context: ./php-fpm/build
    working_dir: /var/www/html
    volumes:
      - ./php-fpm/conf/php.ini:/etc/php.ini
      - ./php-fpm/conf/www.conf:/etc/php-fpm.d/www.conf
      - ./src/project:/var/www/html
      - ${HOME}/.composer:/home/user/.composer
    expose:
      - "9000"
    environment:
      - HOST_USER=${HOST_UID:-1001}
      - HOST_GROUP=${HOST_GID:-1001}
    env_file:
      - ./php-fpm/conf/env
    #restart: always
networks:
  default:
    external:
      name: nginx_proxy
